### ISSUE TITLE
Metric "Sonar analysis age" requires project, not component id

### ISSUE THREAD

**Issue by matthijsmaat** [ICTU/quality-report#117]
QR can handle "sub modules" in Sonar. The metric "Sonar analysis age" however requires a project id, which is not availabe for a sub module. Effect is a "niet alle benodigde bronnen beschikbaar" in the QR for this metric.

**Comment by fniessink** [comment]
In SonarQube 6.4 and newer the information returned by api/components/show includes the analysis date of the component.

**Comment by fniessink** [comment]
HQ/master branch contains a (partial) fix that should work with SonarQube 6.4 or newer. Do we have a project that uses both submodules as well as SonarQube >= 6.4 to test it with?

**Comment by matthijsmaat** [comment]
Yes, the new Inspectieviews has Sonar 6.4 and one Sonarproject that analyses the quality for various components as a whole. The fix works, the "Sonar analysis age" metric on a specific component now reports the actual analysis age.
