### ISSUE TITLE
IE 11: not displaying dashboard in Jenkins

### ISSUE THREAD

**Issue by pimma** [ICTU/quality-report#130]
Issue when using IE11 is used and the 'Kwaliteitsrapport' is clicked, this results in no dashboard being displayed. 

Browser console log: 'Id expected' File: bundel.js, row 1, column 323

**Comment by fniessink** [comment]
Release 2.13.2 hopefully contains a fix for this issue. Please test.

**Comment by fniessink** [comment]
@pimma mailed me before: "Sommige gebruikers hier hebben een iets andere versie van IE11 waarbij het dashboard wel geladen wordt nadat je de pagina herlaadt (in eerste instantie is deze ook blank). Bij de versie die ik heb heeft herladen geen effect. Verschil in versie is miniem qua versienr (11.0.6900.18792 vs 11.0.6900.188xx) dus ik vraag me hardop af of dat het issue is."

**Comment by fniessink** [comment]
@pimma Can you please double check the IE version numbers? Thanks.

**Comment by pimma** [comment]
De IE versie waarbij het issue bij mij optreedt is 11.0.9600.18816.   Het is alleen niet zo dat iedereen die deze IE versie heeft het probleem heeft. Soms doet ie het ook wel met deze versie. Dat maakt het een schimmig issue..

**Comment by milenk** [comment]
Cannot reproduce. Closing the issue.

Probable cause were issues with an old version of webpack, giving the same symptoms.
