### ISSUE TITLE
performance metric for load testcases gives incorrect number

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-report#133]
Apparently this metric looks at the whole row of results (history), instead of only the latest run?
Metric:
1 van de 10 performanceloadtestgevallen van <Application> overschrijden de maximale responstijd.

**Comment by fniessink** [comment]
De metric_source.SilkPerformerTestReport looks at all table rows in the performance report. This will incorrectly take rows from the trend table into account.

**Comment by fniessink** [comment]
This should be fixed in the upcoming 2.13.3 release.
