### ISSUE TITLE
QualityGateTracker [2.16.0]: standard values incorrect

### ISSUE THREAD

**Issue by pimma** [ICTU/quality-report#158]
The standard values for the metric coupled with metric_source.QualityGateTracker should be reversed.

Currently:
0 = green
=>1 red

Should be:
0= red
=>1 green

The QualityGateTracker relates to Test progress jirafilters (metric_source.JiraFilter)

**Comment by fniessink** [comment]
Reversing the direction of the metric (higher is better instead of lower is better) would make this metric the odd one out compared to all the other "trackers" where lower is better. Can't you just reverse your Jira filter?

**Comment by pimma** [comment]
Looking into that..

**Comment by pimma** [comment]
Solved by reverting JIRA-filters.
Please close bug
