### ISSUE TITLE
support for branch analysis in HQ

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-report#164]
Since SonarQube version 6.7 there is the possibility to analyse source code with the sonar.branch.name parameter when this parameter is passed during analysis. 
See also: https://docs.sonarqube.org/display/PLUG/Branch+Plugin
To get the results of an analysed branch in HQ, the optional parameter &branch=<branch_name> should be provided in the web api.

Please add functionality to use/configure this optional parameter in the project definition(s). 

REMINDER, this optional argument only works for version 6.7 and newer.

**Comment by milenk** [comment]
In the project definition, we keep the syntax SONAR: 'nl.ictu:quality_report:<branch>', and we split the branch later, depending on sonar version.

E.g. in sonar.py funct. version:

```
  def version(self, product: str) -> str:
        """ Return the version of the product. """

        #if sonarcube versie >= 6.7
        #   product.split(':') -> (product, branch)

```
It has to be done for all other methods that use "product" as argument.

Test with vastgoed project.
