### ISSUE TITLE
Make 'Birt Jira-metrics' (US/LTCs) available without the need for Birt

### ISSUE THREAD

**Issue by pimma** [ICTU/quality-report#177]
Jira usually holds a wealth of information regarding Scrum workflow. Currently many Jira-metrics are coupled with Birt reporting as is implemented at ICTU. It can be beneficial if these metrics can also be`accessed` by means of metrics that don't require Birt.

It involves these metrics:

- UserStoriesNotApproved
- LogicalTestCasesNotApproved
- NumberofManualLogicalTestCases
- UserStoriesWithTooFewLogicalTestCases
- ReadyUserStoryPoints
- UserStoriesNotReviewed
- TeamProgress
- ManualLogicalTestCases

metric_source.Birt

**Comment by pimma** [comment]
What is the current view regarding this feature?

**Comment by fniessink** [comment]
Sorry, no concrete plans at the moment.
