### ISSUE TITLE
Feature: Add metric for the number of user stories "In Progress"

### ISSUE THREAD

**Issue by milenk** [ICTU/quality-report#185]
Add a metric that reports the number of user stories in progress in the current sprint and becomes yellow or red if there are too many open stories.

The concrete metric source for this metric is a JiraFilter. Implementation can be similar to the other issue trackers.

**Comment by fniessink** [comment]
Please update https://github.com/ICTU/quality-report/wiki/Issue-tracker-metrics when done.
