### ISSUE TITLE
Bug with new SONAR-api?

### ISSUE THREAD

**Issue by matthijsmaat** [ICTU/quality-report#2]
Seems that the quality report uses a SONAR api to retrieve the value of certain metrics (e.g. NOSONAR) that no longer works (at least, works correctly). The quality report indicates that code contains zero NOSONAR issues, while SONAR itself states a few dozen. 

Retrieving issues by hand using the new "issues" api, gives the correct result.

**Comment by fniessink** [comment]
Fixed in version 1.62.4.
