### ISSUE TITLE
Deprecated SonarQube metrics are being used (if SonarQube 6.2+ is used)

### ISSUE THREAD

**Issue by Erik-Stel** [ICTU/quality-report#246]
Deprecated SonarQube test coverage metrics are being used (see links below). Since SonarQube 6.2 these metrics are no longer available. For new projects (where this metric is not calculated yet) it will lead to missing metrics. Older projects will probably just show the 'old' information from the SonarQube pre 6.2 era (which could just as well be yesterday if SonarQube 5.x was used yesterday).

[OVERALL_LINE_COVERAGE](http://javadocs.sonarsource.org/6.3/apidocs/org/sonar/api/measures/CoreMetrics.html#OVERALL_LINE_COVERAGE)
[OVERALL_BRANCHE_COVERAGE](http://javadocs.sonarsource.org/6.3/apidocs/org/sonar/api/measures/CoreMetrics.html#OVERALL_BRANCH_COVERAGE)

**Comment by fniessink** [comment]
HQ doesn't use the Plugin API but only the Web Api. The documentation at https://docs.sonarqube.org/display/SONAR/Metric+Definitions doesn't mention any deprecated coverage metrics.

**Comment by Erik-Stel** [comment]
When using the web API on a new (source code) component, the following JSON is result when using `overall_line_coverage` as metric:
```JSON
{
	"component": {
		"id": "id",
		"key": "key",
		"name": "name",
		"description": "description",
		"qualifier": "TRK",
		"measures": []
	}
}
```

When using the same web API call with `line_coverage` on the same component the following is the result (no I did not fake the metric result, only the identification parts ;-):
```JSON
{
	"component": {
		"id": "id",
		"key": "key",
		"name": "name",
		"description": "description",
		"qualifier": "TRK",
		"measures": [
			{
				"metric": "line_coverage",
				"value": "100.0",
				"periods": [
					{
						"index": 1,
						"value": "0.0"
					}
				]
			}
		]
	}
}
```

On 'old' components the web API does however return a result similar to the later when requesting the `overall_line_coverage`. Can't reach SonarQube right now to validate the data is also 'old'. Will do that as soon as I have access again.

**Comment by Erik-Stel** [comment]
I have sent pm with example (can't share it here because of confidentiality) which seems to be in line with my assumption. If overall coverage is requested through web API it shows 'old' values which are not in line with the values shown in SonarQube UI. If 'regular' coverage is requested through web API it does match the values shown in SonarQube UI.

**Comment by fniessink** [comment]
Okay, conclusion is that SonarQube >= 6.2 doesn't distinguish between unit tests and integration tests (https://docs.sonarqube.org/display/SONAR/Release+6.2+Upgrade+Notes) any more and support for this can be removed from HQ.
