### ISSUE TITLE
Add metrics for difference between actual SonarQube profiles and standard profiles

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-report#247]
Allow for reporting on the difference between actual SonarQube profiles compared to standard profiles. Metrics per language. One per language for number of rules present in standard but not in actual profile. One per language for number of rules with lower severity. 

Implementation: rely on SonarQube API for differences? Assume the standard profile is in SonarQube? How can we know it hasn't been changed? Upload the standard profile? Or download the actual profile and have HQ do the comparison?

**Comment by GTekieli** [comment]
The comparison should be based on the inheritance of the profiles. The active profile should be compared to its parent recursively until we reach the root Sonar way profile.
