### ISSUE TITLE
Enable unit test coverage information from other sources than Sonar

### ISSUE THREAD

**Issue by matthijsmaat** [ICTU/quality-report#262]
Now  QR gets unit test coverage information from Sonar. In some cases, Sonar however rapports coverage values that differ from the unit test coverage files generated by for instance Jacoco. Could the coverage files be used as an alternative source for coverage information?

**Comment by fniessink** [comment]
Available in HQ 2.39.0. See https://github.com/ICTU/quality-report/wiki/Unit-test-coverage-metrics.
