### ISSUE TITLE
Use detailpanel in HQ for details

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-report#266]
Recently #209  - Implement extra information for metrics was implemented. Every metric should have a button that opens/hides collapsible extra information panel. 

This is a really nice feature, except the fact that also the comments (adjustment for a metric norm, reason why metric is not measurable, etc.) are also moved to the detail panel. 
Suggestion is to re-enable the comment section again and add some details for the specific metric in the detailpanel. For example explanations of what OpenVAS, OWASP, ZAP Scan are and why a certain metric is that important.

**Comment by milenk** [comment]
done as #265
