### ISSUE TITLE
Jenkins jobs in information pane are not clickable

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-report#287]
Jenkins jobs in information pane are not clickable

After the introduction of #276 these jobs are not clickable anymore. 
A workaround is to use control or command(for Mac) and click on the link or use the open in new tab/on new page option.
A possible solution is to add a target=”_blank” to the link.

**Comment by fniessink** [comment]
This problem is caused by Jenkins using an iframe to show the quality report. Our new internal setup with the separate webserver doesn't have this problem.
