### ISSUE TITLE
Bug: Nexus(ArchiveSystem) opening/reading URL incorrectly reads URL-content

### ISSUE THREAD

**Issue by Erik-Stel** [ICTU/quality-report#298]
(Should probably provide test to show this fails, but this is faster)

In `__init__` the `_url_open` instance variable is set to either a provided callable or to the default `UrlOpener`. In the later case (my situation) the assigned value is not a `UrlOpener`, but the content read using `url_read`. In the method `last_changed_date` this will result in an exception since a `string` does not understand the `read` message sent.

```
    def __init__(self, url_open: Callable[[str], TextIO] = None, **kwargs) -> None:
        self._url_open = url_open or url_opener.UrlOpener(**kwargs).url_read
        super().__init__()

    def last_changed_date(self, path: str) -> DateTime:
        try:
            contents = self._url_open(path).read()
```

**Comment by milenk** [comment]
solved in release v2.46.2
