### ISSUE TITLE
Extend SonarQube's false-positive metric with won't fix

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-report#334]
SonarQube's false-positive metric is used in HQ to measure the total of suppressed false-positives. 
Because it is also possible to suppress a Sonar violation with "won't fix" I would like to suggest to combine these two violations into one metric:

**Old description:**
<ApplicationXYZ> bevat x violations die zijn gemarkeerd als false positive. 
**New description:**
<ApplicationXYZ> bevat x violations die zijn gemarkeerd als false positive of won't fix 

This way we have the following metrics in HQ:
- ​the number of suppressions in **code** (//NOSONAR) and a metric for 
- the number of suppressions in **SonarQube** (combination of false positive and won't fix)

New URL for HQ: http://www.ApplicationXYZ:9000/issues?resolutions=FALSE-POSITIVE%2CWONTFIX

**Comment by pimma** [comment]
It would make a nice addition to the false-positive-metric. However combining these two parameters in one metric requires providing two sources for this metric in the project definition which can make it more difficult to develop. Wouldnt it be easier to create a metric for the number of 'wont fix's' in SonarQube?

**Comment by denniebouman** [comment]
@pimma  It's not necessary to configure something for this (new) metric in the project definition. Everything is covered behind the scenes ;-) 
To me it sound better to group suppressions by code/tool, but i'm fine with your suggestion also.
It's up to @fniessink to decide i think.
