### ISSUE TITLE
Wiki refers to incorrect metric_source

### ISSUE THREAD

**Issue by Erik-Stel** [ICTU/quality-report#448]
(No time to do PR so creating issue)
https://github.com/ICTU/quality-report/wiki/Aggregated-test-coverage-metrics refers to `metric_source.AggregatedTestCoverageReport` which should be `metric_source.AggregatedCoverageReport`. A bit of inconsistency is the fact that for requirement it is `requirement.AggregatedTestCoverage`.

**Comment by fniessink** [comment]
Fixed the Wiki documentation.
