### ISSUE TITLE
Add an integration test suite

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-report#5]
- Generate a report with no sources
- Generate a report with sources, but no source ids
- Generate the quality report of the quality report software.

**Comment by greyarch** [comment]
This should not be an issue, but a project - https://github.com/ICTU/quality-report/projects

**Comment by greyarch** [comment]
Created one here https://github.com/ICTU/quality-report/projects/1

**Comment by fniessink** [comment]
Cool. Thanks.
