### ISSUE TITLE
GitlabCI has the result capped to 20 branches

### ISSUE THREAD

**Issue by milenk** [ICTU/quality-report#645]
het resultaat lijkt te zijn gemaximeerd op 20, ook al zijn er meer branches in het project. misschien pagineren we niet door de resultaten van gitlab? de default voor de gitlab api lijkt heel toevallig ook 20

**Comment by enrico2828** [comment]
I encountered this bug when setting up the CI metric. It seems that when there is more then 20 branches with pipeline in a project, only 20 will be displayed. Coincidentally, the Gitlab API by default paginates at 20 results .. 
However, this is now more a theoretical bug to us as we only look at the build results of a very few branches in a given project.
