### ISSUE TITLE
Remove barely used metrics

### ISSUE THREAD

**Issue by matthijsmaat** [ICTU/quality-report#83]
Several metrics are barely used. In specific uses of the optional requirement concept (added_requirements= Project.optional_requirements() - {}), these metric show up on the quality report as "not avaliable" or "not configured". For exapmple: requirement.TrackTechnicalDebt and requirement.TrackReadyUS.

**Comment by milenk** [comment]
Not specific enough! TeamProgress metric removed in #206.
